"use client";

import { useRouter } from "next/navigation";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { X } from "lucide-react";

export default function TermsPage() {
  const router = useRouter();

  return (
    <div className="flex flex-col min-h-screen bg-background">
      <Header />

      <main className="flex-grow container mx-auto px-4 py-12 md:py-16 relative">
        {/* Close Button */}
        <button
          onClick={() => router.back()}
          className="absolute top-4 right-4 text-muted-foreground hover:text-foreground transition"
        >
          <X className="h-6 w-6" />
        </button>

        <Card className="max-w-4xl mx-auto">
          <CardHeader>
            <CardTitle className="text-3xl font-headline">Terms & Conditions</CardTitle>
          </CardHeader>

          <CardContent className="space-y-6 text-muted-foreground">
            <section>
              <h3 className="font-bold text-xl text-foreground mb-2">1. Acceptance of Terms</h3>
              <p>
                By creating an account or using LifeSignal AI, you agree to these Terms & Conditions. 
                If you do not agree, you may not use the service.
              </p>
            </section>

            <section>
              <h3 className="font-bold text-xl text-foreground mb-2">2. User Responsibilities</h3>
              <p>
                You agree that all information you provide is accurate. You are responsible for maintaining
                the confidentiality of your login credentials and for all activity under your account.
              </p>
            </section>

            <section>
              <h3 className="font-bold text-xl text-foreground mb-2">3. Emergency Contact Usage</h3>
              <p>
                You confirm that your emergency contact has consented to receive alerts, notifications,
                and calls generated by LifeSignal AI in emergency situations.
              </p>
            </section>

            <section>
              <h3 className="font-bold text-xl text-foreground mb-2">4. Limitations of Service</h3>
              <p>
                LifeSignal AI is not a replacement for 911 or emergency services. We cannot guarantee
                delivery of notifications or calls due to carrier issues, network failures, or user device
                restrictions.
              </p>
            </section>

            <section>
              <h3 className="font-bold text-xl text-foreground mb-2">5. Liability Disclaimer</h3>
              <p>
                LifeSignal AI is not liable for damages resulting from missed alerts, system downtime,
                inaccurate data, or misuse of the app.
              </p>
            </section>

            <section>
              <h3 className="font-bold text-xl text-foreground mb-2">6. Modifications</h3>
              <p>
                We may update these Terms & Conditions from time to time. Continued use of the service
                constitutes acceptance of the revised terms.
              </p>
            </section>
          </CardContent>
        </Card>
      </main>

      <Footer />
    </div>
  );
}
